# Practice Exercise: Importing data & Exploring data(manipulation)

## Context:
- The data is about NBA (National Basketball Association) games from 2004 season to Dec, 2020.
- We'll be focusing on practicing importing data and data manipulation techniques learned in the course. But the dataset is also popular to be used for predicting NBA games winners.
- We've made minor changes on the data to fit this exercise, such as changing the column names. Check out the original source if you are interested in using this data for other purposes (https://www.kaggle.com/nathanlauga/nba-games)

## Dataset Description:

We'll work on two datasets (in two separate csv files):

  - **games**: each game from 2004 season to Dec 2020, including information about the two teams in each game, and some details like number of points, etc
  - **teams**: information about each team played in the games
  
Assume we want to study the game level data, but with detailed information about each team. We'll need to combine these two datasets together.

## Objective: 
   - Load/examine/subset/rename/change dtypes of columns for each individual dataset
   - Combine them into a single dataset, and export it
   - Explore the final dataset by subsetting or sorting

### 1. Import the libraries

In [1]:
import pandas as pd

### 2. Load the data in `games.csv` as a DataFrame called `games`

Save the csv file under the same directory as the notebook if not typing the full path.

In [2]:
games = pd.read_csv("games.csv")

### 3. Look at the first 5 rows of the DataFrame

In [3]:
games.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0

### 4. Look at the columns of the DataFrame

In [4]:
games.columns

Index(['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'PTS_home', 'FG_PCT_home',
       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away',
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
       'REB_away', 'HOME_TEAM_WINS'],
      dtype='object')

### 5. Reassign `games` as its subset of the columns 'GAME_DATE', 'GAME_STATUS_TEXT', 'TEAM_ID_home', 'TEAM_ID_away', 'POINTS_home', 'POINTS_away', 'HOME_TEAM_WINS'

We'll only keep some columns about the games

In [5]:
games = games[['GAME_DATE_EST', 'GAME_STATUS_TEXT',
               'TEAM_ID_home', 'TEAM_ID_away',
               'PTS_home', 'PTS_away',
               'HOME_TEAM_WINS']]

### 6. Look at the new `games` DataFrame's first 5 rows, and info summary

In [6]:
games.head()

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1
2,2022-12-21,Final,1610612739,1610612749,114.0,106.0,1
3,2022-12-21,Final,1610612755,1610612765,113.0,93.0,1
4,2022-12-21,Final,1610612737,1610612741,108.0,110.0,0

In [7]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  object
 1   GAME_STATUS_TEXT  26651 non-null  object
 2   TEAM_ID_home      26651 non-null  int64
 3   TEAM_ID_away      26651 non-null  int64
 4   PTS_home          26552 non-null  float64
 5   PTS_away          26552 non-null  float64
 6   HOME_TEAM_WINS    26651 non-null  int64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.4+ MB

### 7. Convert `GAME_DATE` to a `datetime` dtype

In [8]:
games['GAME_DATE_EST']= pd.to_datetime(games['GAME_DATE_EST'])

In [9]:
games['GAME_DATE_EST']

0       2022-12-22
1       2022-12-22
2       2022-12-21
3       2022-12-21
4       2022-12-21
           ...
26646   2014-10-06
26647   2014-10-06
26648   2014-10-06
26649   2014-10-05
26650   2014-10-04
Name: GAME_DATE_EST, Length: 26651, dtype: datetime64[ns]

### 8. Convert `GAME_STATUS_TEXT` to a `string` dtype

In [10]:
games['GAME_STATUS_TEXT'] = games['GAME_STATUS_TEXT'].astype('string')

In [11]:
games['GAME_STATUS_TEXT']

0        Final
1        Final
2        Final
3        Final
4        Final
         ...
26646    Final
26647    Final
26648    Final
26649    Final
26650    Final
Name: GAME_STATUS_TEXT, Length: 26651, dtype: string

### 9. Look at the info summary of the DataFrame to verify the changes

In [12]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  datetime64[ns]
 1   GAME_STATUS_TEXT  26651 non-null  string
 2   TEAM_ID_home      26651 non-null  int64
 3   TEAM_ID_away      26651 non-null  int64
 4   PTS_home          26552 non-null  float64
 5   PTS_away          26552 non-null  float64
 6   HOME_TEAM_WINS    26651 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), string(1)
memory usage: 1.4 MB

### 10. Load the data in `teams.csv` as a DataFrame called `teams`, and look at its first 5 rows, and its columns

In [13]:
teams = pd.read_csv('teams.csv')

In [14]:
teams.head()

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,0,1610612737,1949,2019,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Lloyd Pierce,Erie Bayhawks
1,0,1610612738,1946,2019,BOS,Celtics,1946,Boston,TD Garden,18624.0,Wyc Grousbeck,Danny Ainge,Brad Stevens,Maine Red Claws
2,0,1610612740,2002,2019,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Tom Benson,Trajan Langdon,Alvin Gentry,No Affiliate
3,0,1610612741,1966,2019,CHI,Bulls,1966,Chicago,United Center,21711.0,Jerry Reinsdorf,Gar Forman,Jim Boylen,Windy City Bulls
4,0,1610612742,1980,2019,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Mark Cuban,Donnie Nelson,Rick Carlisle,Texas Legends

### 10. Load the data in `teams.csv` as a DataFrame called `teams`, and look at its first 5 rows, and its columns

In [15]:
teams.columns

Index(['LEAGUE_ID', 'TEAM_ID', 'MIN_YEAR', 'MAX_YEAR', 'ABBREVIATION',
       'NICKNAME', 'YEARFOUNDED', 'CITY', 'ARENA', 'ARENACAPACITY', 'OWNER',
       'GENERALMANAGER', 'HEADCOACH', 'DLEAGUEAFFILIATION'],
      dtype='object')

### 11. Reassign `teams` as a subset of its columns 'TEAM_ID', 'CITY', 'NICKNAME', and look at its first 5 rows and info summary

We'll only keep some columns about the teams

In [16]:
teams =  teams[['TEAM_ID', 'CITY', 'NICKNAME']]

In [17]:
teams.head()

      TEAM_ID         CITY   NICKNAME
0  1610612737      Atlanta      Hawks
1  1610612738       Boston    Celtics
2  1610612740  New Orleans   Pelicans
3  1610612741      Chicago      Bulls
4  1610612742       Dallas  Mavericks

### 12. Convert both columns `CITY` and `NICKNAME` to a `string` dtype

In [18]:
teams = teams.astype({'CITY': 'string', 'NICKNAME':'string'})

### 13. Verify the changes with the `dtypes` attribute

In [19]:
teams.dtypes

TEAM_ID              int64
CITY        string[python]
NICKNAME    string[python]
dtype: object

In [20]:
games.head(2)

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1

In [21]:
teams.head(2)

      TEAM_ID     CITY NICKNAME
0  1610612737  Atlanta    Hawks
1  1610612738   Boston  Celtics

In [22]:
games_with_home_team = pd.merge(games,teams,left_on='TEAM_ID_home', right_on='TEAM_ID', how='inner')

In [23]:
games_with_home_team.head()

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS,TEAM_ID,CITY,NICKNAME
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1,1610612740,New Orleans,Pelicans
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1,1610612762,Utah,Jazz
2,2022-12-21,Final,1610612739,1610612749,114.0,106.0,1,1610612739,Cleveland,Cavaliers
3,2022-12-21,Final,1610612755,1610612765,113.0,93.0,1,1610612755,Philadelphia,76ers
4,2022-12-21,Final,1610612737,1610612741,108.0,110.0,0,1610612737,Atlanta,Hawks

In [24]:
games_with_home_team = games_with_home_team.rename(columns={'CITY':'city_home','NICKNAME': 'nickname_home'})

In [25]:
games_with_home_team.head(2)

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS,TEAM_ID,city_home,nickname_home
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1,1610612740,New Orleans,Pelicans
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1,1610612762,Utah,Jazz

In [26]:
games_with_both_teams = pd.merge(games_with_home_team,teams,
                                 left_on= 'TEAM_ID_away',
                                 right_on='TEAM_ID')

In [27]:
games_with_both_teams.head(2)

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS,TEAM_ID_x,city_home,nickname_home,TEAM_ID_y,CITY,NICKNAME
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1,1610612740,New Orleans,Pelicans,1610612759,San Antonio,Spurs
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1,1610612762,Utah,Jazz,1610612764,Washington,Wizards

In [28]:
games_with_both_teams = games_with_both_teams.rename(columns={'CITY':'city_away','NICKNAME': 'nickname_away'})

In [29]:
games_with_both_teams.head(2)

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS,TEAM_ID_x,city_home,nickname_home,TEAM_ID_y,city_away,nickname_away
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1,1610612740,New Orleans,Pelicans,1610612759,San Antonio,Spurs
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1,1610612762,Utah,Jazz,1610612764,Washington,Wizards

In [30]:
games_with_both_teams.head()

,GAME_DATE_EST,GAME_STATUS_TEXT,TEAM_ID_home,TEAM_ID_away,PTS_home,PTS_away,HOME_TEAM_WINS,TEAM_ID_x,city_home,nickname_home,TEAM_ID_y,city_away,nickname_away
0,2022-12-22,Final,1610612740,1610612759,126.0,117.0,1,1610612740,New Orleans,Pelicans,1610612759,San Antonio,Spurs
1,2022-12-22,Final,1610612762,1610612764,120.0,112.0,1,1610612762,Utah,Jazz,1610612764,Washington,Wizards
2,2022-12-21,Final,1610612739,1610612749,114.0,106.0,1,1610612739,Cleveland,Cavaliers,1610612749,Milwaukee,Bucks
3,2022-12-21,Final,1610612755,1610612765,113.0,93.0,1,1610612755,Philadelphia,76ers,1610612765,Detroit,Pistons
4,2022-12-21,Final,1610612737,1610612741,108.0,110.0,0,1610612737,Atlanta,Hawks,1610612741,Chicago,Bulls

In [31]:
games_with_both_teams = games_with_both_teams.drop(columns=['TEAM_ID_home','TEAM_ID_away',
                                                            'TEAM_ID_x', 'TEAM_ID_y'])

In [32]:
games_with_both_teams.head()

,GAME_DATE_EST,GAME_STATUS_TEXT,PTS_home,PTS_away,HOME_TEAM_WINS,city_home,nickname_home,city_away,nickname_away
0,2022-12-22,Final,126.0,117.0,1,New Orleans,Pelicans,San Antonio,Spurs
1,2022-12-22,Final,120.0,112.0,1,Utah,Jazz,Washington,Wizards
2,2022-12-21,Final,114.0,106.0,1,Cleveland,Cavaliers,Milwaukee,Bucks
3,2022-12-21,Final,113.0,93.0,1,Philadelphia,76ers,Detroit,Pistons
4,2022-12-21,Final,108.0,110.0,0,Atlanta,Hawks,Chicago,Bulls

### 22. Make a copy of `games_with_both_teams` and assign it as `games`

In [33]:
games=games_with_both_teams.copy()

In [34]:
games.columns = games.columns.str.lower()

In [35]:
games.columns

Index(['game_date_est', 'game_status_text', 'pts_home', 'pts_away',
       'home_team_wins', 'city_home', 'nickname_home', 'city_away',
       'nickname_away'],
      dtype='object')

In [36]:
games_with_both_teams.columns

Index(['GAME_DATE_EST', 'GAME_STATUS_TEXT', 'PTS_home', 'PTS_away',
       'HOME_TEAM_WINS', 'city_home', 'nickname_home', 'city_away',
       'nickname_away'],
      dtype='object')

### 26. Check the dimensionality  of `games`

In [37]:
games.shape

(26651, 9)

### Export `games` as a csv file called 'games_transformed.csv', and open the csv file to look at it

Feel free to test the difference of the csv files with or without the argument `index=False`

In [38]:
games.to_csv('games-transformed.csv', index=False)

### Select all the columns of 'number' dtypes from `games`

In [39]:
games.select_dtypes(include='number')

       pts_home  pts_away  home_team_wins
0         126.0     117.0               1
1         120.0     112.0               1
2         114.0     106.0               1
3         113.0      93.0               1
4         108.0     110.0               0
...         ...       ...             ...
26646      93.0      87.0               1
26647      81.0      85.0               0
26648      98.0      95.0               1
26649      99.0      94.0               1
26650      86.0      98.0               0

[26651 rows x 3 columns]

In [40]:
games.select_dtypes(exclude='number')

,game_date_est,game_status_text,city_home,nickname_home,city_away,nickname_away
0,2022-12-22,Final,New Orleans,Pelicans,San Antonio,Spurs
1,2022-12-22,Final,Utah,Jazz,Washington,Wizards
2,2022-12-21,Final,Cleveland,Cavaliers,Milwaukee,Bucks
3,2022-12-21,Final,Philadelphia,76ers,Detroit,Pistons
4,2022-12-21,Final,Atlanta,Hawks,Chicago,Bulls
...,...,...,...,...,...,...
26646,2014-10-06,Final,Atlanta,Hawks,New Orleans,Pelicans
26647,2014-10-06,Final,Chicago,Bulls,Washington,Wizards
26648,2014-10-06,Final,Los Angeles,Lakers,Denver,Nuggets
26649,2014-10-05,Final,Toronto,Raptors,Sacramento,Kings
26650,2014-10-04,Final,Miami,Heat,New Orleans,Pelicans

In [41]:
games.head()

,game_date_est,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
0,2022-12-22,Final,126.0,117.0,1,New Orleans,Pelicans,San Antonio,Spurs
1,2022-12-22,Final,120.0,112.0,1,Utah,Jazz,Washington,Wizards
2,2022-12-21,Final,114.0,106.0,1,Cleveland,Cavaliers,Milwaukee,Bucks
3,2022-12-21,Final,113.0,93.0,1,Philadelphia,76ers,Detroit,Pistons
4,2022-12-21,Final,108.0,110.0,0,Atlanta,Hawks,Chicago,Bulls

In [42]:
games.loc[0]

game_date_est       2022-12-22 00:00:00
game_status_text                  Final
pts_home                          126.0
pts_away                          117.0
home_team_wins                        1
city_home                   New Orleans
nickname_home                  Pelicans
city_away                   San Antonio
nickname_away                     Spurs
Name: 0, dtype: object

In [43]:
games.iloc[0]

game_date_est       2022-12-22 00:00:00
game_status_text                  Final
pts_home                          126.0
pts_away                          117.0
home_team_wins                        1
city_home                   New Orleans
nickname_home                  Pelicans
city_away                   San Antonio
nickname_away                     Spurs
Name: 0, dtype: object

In [44]:
games=games.set_index('game_date_est')

In [45]:
games.index

DatetimeIndex(['2022-12-22', '2022-12-22', '2022-12-21', '2022-12-21',
               '2022-12-21', '2022-12-21', '2022-12-21', '2022-12-21',
               '2022-12-21', '2022-12-21',
               ...
               '2014-10-07', '2014-10-07', '2014-10-07', '2014-10-07',
               '2014-10-06', '2014-10-06', '2014-10-06', '2014-10-06',
               '2014-10-05', '2014-10-04'],
              dtype='datetime64[ns]', name='game_date_est', length=26651, freq=None)

In [46]:
games.loc['2020-12-18']

,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
game_date_est,,,,,,,,
2020-12-18,Final,107.0,113.0,0,Indiana,Pacers,Philadelphia,76ers
2020-12-18,Final,105.0,117.0,0,Toronto,Raptors,Miami,Heat
2020-12-18,Final,119.0,83.0,1,New York,Knicks,Cleveland,Cavaliers
2020-12-18,Final,89.0,113.0,0,Boston,Celtics,Brooklyn,Nets
2020-12-18,Final,127.0,113.0,1,New Orleans,Pelicans,Milwaukee,Bucks
2020-12-18,Final,103.0,105.0,0,Oklahoma City,Thunder,Chicago,Bulls
2020-12-18,Final,129.0,96.0,1,Denver,Nuggets,Portland,Trail Blazers
2020-12-18,Final,113.0,114.0,0,Phoenix,Suns,Los Angeles,Lakers

In [47]:
games.sort_index().loc['2020-12-18':'2020-12-19']

,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
game_date_est,,,,,,,,
2020-12-18,Final,107.0,113.0,0,Indiana,Pacers,Philadelphia,76ers
2020-12-18,Final,105.0,117.0,0,Toronto,Raptors,Miami,Heat
2020-12-18,Final,119.0,83.0,1,New York,Knicks,Cleveland,Cavaliers
2020-12-18,Final,103.0,105.0,0,Oklahoma City,Thunder,Chicago,Bulls
2020-12-18,Final,127.0,113.0,1,New Orleans,Pelicans,Milwaukee,Bucks
2020-12-18,Final,129.0,96.0,1,Denver,Nuggets,Portland,Trail Blazers
2020-12-18,Final,89.0,113.0,0,Boston,Celtics,Brooklyn,Nets
2020-12-18,Final,113.0,114.0,0,Phoenix,Suns,Los Angeles,Lakers
2020-12-19,Final,116.0,117.0,0,Memphis,Grizzlies,Atlanta,Hawks
2020-12-19,Final,99.0,96.0,1,Washington,Wizards,Detroit,Pistons
2020-12-19,Final,120.0,117.0,1,Orlando,Magic,Charlotte,Hornets

In [48]:
games.loc[['2020-12-18','2019-12-18']]

,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
game_date_est,,,,,,,,
2020-12-18,Final,107.0,113.0,0,Indiana,Pacers,Philadelphia,76ers
2020-12-18,Final,105.0,117.0,0,Toronto,Raptors,Miami,Heat
2020-12-18,Final,119.0,83.0,1,New York,Knicks,Cleveland,Cavaliers
2020-12-18,Final,89.0,113.0,0,Boston,Celtics,Brooklyn,Nets
2020-12-18,Final,127.0,113.0,1,New Orleans,Pelicans,Milwaukee,Bucks
2020-12-18,Final,103.0,105.0,0,Oklahoma City,Thunder,Chicago,Bulls
2020-12-18,Final,129.0,96.0,1,Denver,Nuggets,Portland,Trail Blazers
2020-12-18,Final,113.0,114.0,0,Phoenix,Suns,Los Angeles,Lakers
2019-12-18,Final,100.0,98.0,1,Cleveland,Cavaliers,Charlotte,Hornets
2019-12-18,Final,99.0,112.0,0,Detroit,Pistons,Toronto,Raptors
2019-12-18,Final,109.0,110.0,0,Washington,Wizards,Chicago,Bulls
2019-12-18,Final,104.0,108.0,0,Philadelphia,76ers,Miami,Heat
2019-12-18,Final,99.0,107.0,0,Minnesota,Timberwolves,New Orleans,Pelicans
2019-12-18,Final,126.0,122.0,1,Oklahoma City,Thunder,Memphis,Grizzlies
2019-12-18,Final,113.0,104.0,1,Denver,Nuggets,Orlando,Magic
2019-12-18,Final,103.0,109.0,0,Dallas,Mavericks,Boston,Celtics
2019-12-18,Final,122.0,112.0,1,Portland,Trail Blazers,Golden State,Warriors

In [49]:
games[games['pts_home']>150]

,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
game_date_est,,,,,,,,
2022-11-15,Final,153.0,121.0,1,Sacramento,Kings,Brooklyn,Nets
2022-02-25,Final,153.0,157.0,0,Washington,Wizards,San Antonio,Spurs
2021-12-02,Final,152.0,79.0,1,Memphis,Grizzlies,Oklahoma City,Thunder
2021-05-03,Final,154.0,141.0,1,Washington,Wizards,Indiana,Pacers
2020-08-25,Final,154.0,111.0,1,Los Angeles,Clippers,Dallas,Mavericks
2020-01-28,Final,151.0,131.0,1,Milwaukee,Bucks,Washington,Wizards
2020-01-26,Final,152.0,133.0,1,Atlanta,Hawks,Washington,Wizards
2010-03-16,Final,152.0,114.0,1,Phoenix,Suns,Minnesota,Timberwolves
2008-04-06,Final,151.0,147.0,1,Oklahoma City,Thunder,Denver,Nuggets
2008-03-16,Final,168.0,116.0,1,Denver,Nuggets,Oklahoma City,Thunder
2006-12-27,Final,151.0,145.0,1,New York,Knicks,Detroit,Pistons
2006-12-07,Final,157.0,161.0,0,Brooklyn,Nets,Phoenix,Suns
2019-11-30,Final,158.0,111.0,1,Houston,Rockets,Atlanta,Hawks
2019-10-30,Final,158.0,159.0,0,Washington,Wizards,Houston,Rockets
2019-03-01,Final,161.0,168.0,0,Atlanta,Hawks,Chicago,Bulls
2019-01-10,Final,154.0,147.0,1,San Antonio,Spurs,Oklahoma City,Thunder

In [50]:
len(games[games['pts_home'] > 150])

16

### Select the rows with `points_home` greater than 150, and `home_team_wins` not being 1

In [51]:
games[(games['pts_home']>150)&(games['home_team_wins']!=1)]

,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
game_date_est,,,,,,,,
2022-02-25,Final,153.0,157.0,0,Washington,Wizards,San Antonio,Spurs
2006-12-07,Final,157.0,161.0,0,Brooklyn,Nets,Phoenix,Suns
2019-10-30,Final,158.0,159.0,0,Washington,Wizards,Houston,Rockets
2019-03-01,Final,161.0,168.0,0,Atlanta,Hawks,Chicago,Bulls

### Select the rows with `points_home` greater than 150, and `home_team_wins` not being 1, as well as the columns `home_team_wins` and `points_home`

In [52]:
games.loc[(games['pts_home']>150)&(games['home_team_wins']!=1),['home_team_wins','pts_home']]

               home_team_wins  pts_home
game_date_est
2022-02-25                  0     153.0
2006-12-07                  0     157.0
2019-10-30                  0     158.0
2019-03-01                  0     161.0

### Reset the index of `games` back to default and verify the changes

In [53]:
games=games.reset_index()

In [54]:
games.head(2)

,game_date_est,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away
0,2022-12-22,Final,126.0,117.0,1,New Orleans,Pelicans,San Antonio,Spurs
1,2022-12-22,Final,120.0,112.0,1,Utah,Jazz,Washington,Wizards

In [55]:
games['points_total'] = games['pts_home']+ games['pts_away']

In [56]:
games[['pts_home', 'pts_away', 'points_total']]

       pts_home  pts_away  points_total
0         126.0     117.0         243.0
1         120.0     112.0         232.0
2         114.0     106.0         220.0
3         113.0      93.0         206.0
4         108.0     110.0         218.0
...         ...       ...           ...
26646      93.0      87.0         180.0
26647      81.0      85.0         166.0
26648      98.0      95.0         193.0
26649      99.0      94.0         193.0
26650      86.0      98.0         184.0

[26651 rows x 3 columns]

In [60]:
games.nlargest(n=3, columns='points_total')

,game_date_est,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away,points_total
20030,2019-03-01,Final,161.0,168.0,0,Atlanta,Hawks,Chicago,Bulls,329.0
14727,2006-12-07,Final,157.0,161.0,0,Brooklyn,Nets,Phoenix,Suns,318.0
19528,2019-10-30,Final,158.0,159.0,0,Washington,Wizards,Houston,Rockets,317.0

In [61]:
games=games.sort_values(by='points_total')

In [62]:
games.tail(3)

,game_date_est,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away,points_total
19271,2003-10-08,Final,NaN,NaN,0,San Antonio,Spurs,Memphis,Grizzlies,NaN
19278,2003-10-08,Final,NaN,NaN,0,Los Angeles,Lakers,Golden State,Warriors,NaN
19279,2003-10-07,Final,NaN,NaN,0,Los Angeles,Lakers,Golden State,Warriors,NaN

In [63]:
games.iloc[0]

game_date_est       2007-10-19 00:00:00
game_status_text                  Final
pts_home                           36.0
pts_away                           33.0
home_team_wins                        1
city_home                        Boston
nickname_home                   Celtics
city_away                      Brooklyn
nickname_away                      Nets
points_total                       69.0
Name: 13632, dtype: object

In [64]:
games.head()

,game_date_est,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away,points_total
13632,2007-10-19,Final,36.0,33.0,1,Boston,Celtics,Brooklyn,Nets,69.0
19275,2003-10-08,Final,62.0,58.0,1,Indiana,Pacers,Chicago,Bulls,120.0
17807,2004-11-09,Final,64.0,60.0,1,Brooklyn,Nets,Portland,Trail Blazers,124.0
16931,2005-03-13,Final,64.0,62.0,1,Detroit,Pistons,Utah,Jazz,126.0
19137,2003-11-01,Final,73.0,56.0,1,Minnesota,Timberwolves,Toronto,Raptors,129.0

In [65]:
games.iloc[[1,2]]

,game_date_est,game_status_text,pts_home,pts_away,home_team_wins,city_home,nickname_home,city_away,nickname_away,points_total
19275,2003-10-08,Final,62.0,58.0,1,Indiana,Pacers,Chicago,Bulls,120.0
17807,2004-11-09,Final,64.0,60.0,1,Brooklyn,Nets,Portland,Trail Blazers,124.0

In [66]:
games.iloc[:4,:5]

      game_date_est game_status_text  pts_home  pts_away  home_team_wins
13632    2007-10-19            Final      36.0      33.0               1
19275    2003-10-08            Final      62.0      58.0               1
17807    2004-11-09            Final      64.0      60.0               1
16931    2005-03-13            Final      64.0      62.0               1